### ISSUE TITLE
feature gui 코멘트

### ISSUE THREAD

**Issue by ytbeom** [jaemoon-sim/caption-creator#2]

**Comment by ytbeom** [comment]
* 일단 window는 `brew`가 없어서 `pip3 install pyqt5` 하니까 정상 실행은 됐음
  * 돌아가는데 문제 없읍니다!

## 기능상 문제
* 지금 여러줄짜리 자막은 생성이 안됨 (근데 단일 이미지 생성에선 되네?)
* 영상 쪽에서는 시작이 01:00:00,000인가 그래서 지금 버전으로 srt 파일 넣어서 돌리면 앞에 1시간동안 blank.png가 들어가는 자막 영상이 만들어짐 😢 
  * 다빈치 리졸브 같은거에서도 시작이 01:00:00,000 일텐데 혹시 00:00:00,000 으로 세팅해서 사용하는 사람이 있을 것을 대비해 비디오 생성 전에 시작 offset 설정 같은 칸을 하나 뚫어줘도 좋을 듯
* 아마 video_meta.txt의 맨 마지막줄이 duration으로 끝나면 영상이 제대로 안만들어져서 억지로 blank.png를 넣었던걸로 기억함, 지금 만들어지는 video_meta.txt로 만들면 가장 마지막 자막이 엄청 짧게 나오고 끝나버림
* 너무 긴 자막이라 화면 사이즈 넘어가면 프로그램이 죽는데 예외 처리가 되어야 할듯 (일단 멈추고 기존에 만든걸 다 지워버린다든가, 왜 죽었는지를 보여준다든가 등등)
  * 에러 로그
```
['가나다라마바사:아자차카타파하', 'ㅁㄴㅇㄻㄴㅇㄹㄴㅁㅇㄹㄴㅁㅇㄻㄴㅇㄹㄴㅇㄹㅇㄴㄹ']
Traceback (most recent call last):
  File "C:\Users\ytbeom\Documents\GitHub\caption-creator\app.py", line 151, in generateSingleImage
    mm_generator.generate_image([CaptionInfo(99999, 0, 0, self.textInput.toPlainText().split("\n"))], output_path)
  File "C:\Users\ytbeom\Documents\GitHub\caption-creator\mm_generator.py", line 10, in generate_image
    tc = caption.CaptionCreator(caption_info.text)
  File "C:\Users\ytbeom\Documents\GitHub\caption-creator\caption.py", line 53, in __init__
    pxs[capX+nameW+x, capY+y] = (0, 0, 0, 128)
IndexError: image index out of range
```

## UX 개선안
* SRT 파일을 드래그 앤 드롭 하세요 공간이 버튼처럼 안느껴져서 드래그 앤 드롭만 되는 느낌?
* output path는 확실히 버튼 누를때 생성하는게 나은듯, 없는 경우에 에러나고 죽으니까...
* video도 한 탭에서 만들게 하면 이 때도 어디에 저장할지 / 파일이름은 뭘로 할지 입력받으면 좋을듯
* 터미널 같은거 넣어서 진행상황 볼 수 있게 못하려나? ㅎㅎㅎ
* 단일 이미지 생성에서 말하는 사람이랑 자막을 넣는 란을 구분하는건 어떨까? `:` 로 구분하면 되기는 한데 그래도 명시적으로 있음 더 좋지 않나 하는 그런 생각이 들어서 여쭤보았음, 말하는 사람이 없는 자막이면 말하는 사람 란을 비워서 넣는 식으로?
* 너무 긴 자막 넣으면 죽는 경우 + 화면 정중앙 아래에만 자막을 넣는게 아닌 경우 등을 고려해 있으면 좋을 것 같은 기능
  * 폰트 크기, 상하좌우 마진 조절하는 기능
  * 미리보기 기능 (제일 좌우로 긴 자막 가지고 보여주면 제일 좋을것 같긴 함, 넘어가는지 같은걸 미리 확인하는 용도)
* 단일 이미지도 이름 고정하지 말고 입력 받자, 여러개 만들고 싶을때 매번 폴더 들어가서 바꾸기 귀찮을듯
